# baseurl = "https://joostmeijles.github.io/blog"
languageCode = "en"
title = "Blog about Sitecore development"
description = "My personal blog about Sitecore development"
theme = "kiss"
copyright = "&copy; <a href=\"https://github.com/joostmeijles/blog\">Joost Meijles</a> 2018"
disqusShortname = ""
googleAnalytics = "UA-124806744-1"
# Number of posts per page
Paginate = 5
enableRobotsTXT = true
publishDir = "publish" # https://gohugo.io/hosting-and-deployment/hosting-on-github/
image = "favicon.ico"

[params.assets]
customCSS = ["css/custom.css"]

[params.info]
adsense = "" # Adsense ID (ID only, without ca-pub-)
enableSocial = true # Adds OpenGraph and Twitter cards
homeTitle = "Sitecore development by Joost Meijles" # Title for home page
poweredby = true # Adds powered by Hugo and Kiss below Copyright section
related = true # Includes related articles

[params.opengraph.facebook]
admins = [] # array of Facebook IDs
appID = ""
pageID = ""

[params.opengraph.twitter]
page = "" # Twitter Page username. If not set, params.social.twitter will be used.

[params.social]
twitter = "joostmeijles"
github = "joostmeijles"
email = "joost@meijl.es"
linkedin = "joostmeijles"
facebook = ""
instagram = ""
codepen = ""

# '<style>
#   .strava-badge- { display: inline-block; height: 24px; }
#   .strava-badge- img { visibility: hidden; height: 24px; }
#   .strava-badge-:hover { background-position: 0 -37px; }
#   .strava-badge-follow { height: 24px; width: 24px; background: url(//badges.strava.com/echelon-sprite-24.png) no-repeat 0 0; }
# </style>
# <a href="http://strava.com/athletes/43905728/badge" class="strava-badge- strava-badge-follow" target="_blank"><img src="//badges.strava.com/echelon-sprite-24.png" alt="Strava" /></a>'

[taxonomies]
tag ="tags"

# Adding this tag enables RSS feed
[params.rss]
includeContent = true # Includes whole content in rss
authorName = "Joost Meijles"
authorEmail = "joost@meijl.es"

[outputFormats.Algolia]
baseName = "algolia"
isPlainText = true
mediaType = "application/json"
notAlternative = true

[params.algolia]
vars = ["title", "summary", "date", "publishdate", "expirydate", "permalink"]
params = ["categories", "tags"]

[outputs]
home = ["HTML", "RSS", "Algolia"]
