# baseurl = "https://joostmeijles.github.io/blog"
languageCode = "en"
title = "Joost Meijles"
description = "My personal blog about software development"
theme = "kiss"
copyright = "&copy; <a href=\"https://github.com/joostmeijles/blog\">Joost Meijles</a> 2019"
disqusShortname = ""
googleAnalytics = "UA-124806744-1"
# Number of posts per page
Paginate = 5
enableRobotsTXT = true
publishDir = "publish" # https://gohugo.io/hosting-and-deployment/hosting-on-github/
image = "favicon.ico"

[params.info]
adsense = "" # Adsense ID (ID only, without ca-pub-)
enableSocial = true # Adds OpenGraph and Twitter cards
homeTitle = "Software development by Joost Meijles" # Title for home page
poweredby = true # Adds powered by Hugo and Kiss below Copyright section
related = true # Includes related articles

[params.opengraph.facebook]
admins = [] # array of Facebook IDs
appID = ""
pageID = ""

[params.opengraph.twitter]
page = "" # Twitter Page username. If not set, params.social.twitter will be used.

[params.social]
twitter = "joostmeijles"
github = "joostmeijles"
email = "joost@meijl.es"
linkedin = "joostmeijles"
facebook = ""
instagram = ""
codepen = ""

[taxonomies]
tag ="tags"

# Adding this tag enables RSS feed
[params.rss]
includeContent = true # Includes whole content in rss
authorName = "Joost Meijles"
authorEmail = "joost@meijl.es"

[outputFormats.Algolia]
baseName = "algolia"
isPlainText = true
mediaType = "application/json"
notAlternative = true

[outputFormats.Serviceworker]
baseName = "serviceworker"
isPlainText = true
mediaType = "application/javascript"
notAlternative = true

[params.algolia]
vars = ["title", "summary", "date", "publishdate", "expirydate", "permalink", "content"]
params = ["categories", "tags"]

[outputs]
home = ["HTML", "RSS", "Algolia", "Serviceworker"]
