[build]
    publish = "publish"
    command = "npm run build -- -b $URL"
    functions = "functions/"

[build.environment]
   HUGO_VERSION = "0.57.2"

[context.deploy-preview]
    command = "npm run build -- -b $DEPLOY_URL -F"
